[build]
    functions = "functions"
# [[redirects]]
#     from = "/api/*"
#     to = "/.netlify/functions/:splat"
#     status = 200
[[redirects]]
    from = "/"
    to = "/.netlify/functions/app/getip"
    status = 200

# [[redirects]]
#     from = "/*"
#     to = "/index"
#     status = 200
   

